### ISSUE TITLE
Can't load downstream packages after load_all()

### ISSUE THREAD

**Issue by pitakakariki** [hadley/devtools#1045]
In the working directory of a project based on a local fork of https://github.com/lme4/lme4:

``` r
> devtools::load_all()
Loading lme4
Loading required package: Matrix
> library(MEMSS)
Error: package ‘lme4’ required by ‘MEMSS’ could not be found
```

The error is thrown from `base::.getRequiredPackages2`, because it can't work out the version of the package loaded by `devtools::load_all`. The function `.findVersion` is defined inside `base::getRequiredPackages2`:

``` r
    .findVersion <- function(pkg, lib.loc = NULL) {
        pfile <- system.file("Meta", "package.rds", package = pkg, 
            lib.loc = lib.loc)
        if (nzchar(pfile)) 
            as.numeric_version(readRDS(pfile)$DESCRIPTION["Version"])
    }
```

It's not finding `package.rds`, so it's returning `NULL`. This triggers the error here:

``` r
        current <- .findVersion(pkg, lib.loc)
        if (is.null(current)) 
            stop(gettextf("package %s required by %s could not be found", 
                sQuote(pkg), sQuote(pkgname)), call. = FALSE, 
                domain = NA)
```

**Comment by jimhester** [comment]
If this was using `utils::packageVersion()` as the comment suggests [wch/r-source/src/library/base/R/library.R#L812-L826](https://github.com/wch/r-source/blob/f5e8102b51880ce89dfd3395a48066c5794fc06b/src/library/base/R/library.R#L812-L826) this would work fine. But as you noted because `load_all()` does not create a `package.rds` file this breaks.

We could insert a shim `.getRequiredPackages2` in devtools to fix this I suppose although I think it is best to keep shims to a minimum...

**Comment by hadley** [comment]
Moved to pkgload, and looks like it's unfixable unfortunately.
