### ISSUE TITLE
Explore use parLapply instead of mclapply

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#1127]
So that people can do parallel checks on windows.

The trick will be the progress updates. Might be able to write to a file or use a named pipe (need to check if named pipes work on windows)

**Comment by gaborcsardi** [comment]
FYI, pipes definitely work on windows, e.g. https://github.com/MangoTheCat/rcmdcheck/blob/f51b1407b1f0b7bbebad798b2f01ace6db0ea88f/R/safe_system.R#L26-L38 
opens a pipe and calls a callback function for every line. I checked it on windows as well.

Since `pipe` starts a new process, you don't even need `parLapply`, because that's an extra process again. 

The alternative is just to read the output log files line by line, while the check is writing it. This is not completely trivial to do in R in a portable way (seeking in R is not reliable on windows), but I remember that I managed to make it work. I should be able to find the code, I abandoned it in favour of the `pipe` approach.

**Comment by hadley** [comment]
@gaborcsardi I was thinking you'd initialise the pipe in the parent, and then pass it to the children. The children would communicate status updates by writing to the pipe.

**Comment by hadley** [comment]
This is probably a duplicate of #1106

**Comment by gaborcsardi** [comment]
@hadley That certainly looks like a good option, but the current `devtools` package check code is not really compatible with it. I.e. you cannot simply call `check()` in the child (`parLapply` child or `pipe` child), because that will start another R process. I mean, you can, but there will be an extra process. Which might not be such a big deal, actually.

You would need to have a new version of the `R()` function, that runs `R()` via a pipe. Certainly possible, maybe not even difficult.

**Comment by hadley** [comment]
Right, there's already a _lot_ of processes being created, but it doesn't seem to be a problem.

**Comment by jimhester** [comment]
So since all the work is being done in a new R process (started from `check_built`). Another option would be to start some new child processes with `wait = FALSE`, then `Sys.sleep()` in the parent and check if they are done manually, then start some more. This avoids using any parallel backend and is cross platform. The issues would be the inability to stop the child processes from the R console once started, progress could be tracked by looking for the `COMPLETE` file and I guess there would have to be a timeout for stuck processes.

It would really be nice if R would return the child process id when `wait=FALSE`, but alas...

**Comment by krlmlr** [comment]
@jimhester: This is what BatchJob does with the so-called "multicore" backend. Perhaps it's easier to implement a Windows (or even R-based) version of the [linux-helper](https://github.com/tudo-r/BatchJobs/blob/master/inst/bin/linux-helper)?
