### ISSUE TITLE
Let users run `test` with `export_all=FALSE`

### ISSUE THREAD

**Issue by pitakakariki** [hadley/devtools#1201]
At the moment `test` quietly calls `load_all` with the default `export_all=TRUE`. This means:

- tests for S3 dispatch will pass when they shouldn't (e.g. `print.foo` will work even if it's not exported).
- internal package functions will be left in the search path after `test` has run.

**Comment by hadley** [comment]
But if `export_all = FALSE` you can't test internal functions, which is extremely important. I don't think this should be an option.

**Comment by jimhester** [comment]
Actually devtools runs tests in an environment with the package under tests namespace as a parent. `load_all()` is used just to generate this environment.

So we can set `export_all = FALSE` unconditionally and the internal functions are still able to be tested without dirting the users search path.

#1210 does this.

**Comment by zdk123** [comment]
I found this issue when searching for a work around that wouldn't require changing the devtools. I think this is a generic way to get around the `export_all=TRUE`, with apologies to Hadley for breaking the intended `test` setup.

in a test.R file:
```r
context('...')
#  any setup stuff here
test_that('...', {
  ## set the parent of current environment to the global environment ##
  e <- environment()
  pe <- parent.env(e)
  parent.env(e) <- globalenv()
  pkgpath <- find.package('pkgname')
  devtools::load_all(pkgpath, export_all=FALSE, quiet=TRUE)

  ## Run all tests with nonexported functions ##

  
  ## Reset environment for subsequent tests ##
  parent.env(e) <- pe
  devtools::load_all(pkgpath, export_all=TRUE, quiet=TRUE)
})
```

Since `devtools::test` sets the package namespace as the parent of the testing environment, it's wasn't enough for my purposes to simply reload the package with `export_all=FALSE`, though you need to do that as well. Calls like `match.fun('internal.function')` could still find `internal.function` in the parent environment. 

However, it is possible to manipulate the environment stack from a calling environment.  Above, I've set the parent to the global environment, but one could as easily set it to a new/empty one.

Just make sure to reset / reload or you might break other tests.
