### ISSUE TITLE
Helper to manage Remotes

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#1304]
It would be nice to have a `Remotes` helper. Or maybe `use_package()` could help with this.

**Comment by hadley** [comment]
@gaborcsardi would you consider adding remotes helpers to desc?

**Comment by gaborcsardi** [comment]
Sure, makes sense, I was already thinking about it. How about
* `get_remotes()`
* `set_remotes(remotes)`
* `add_remotes(remotes)`
* `del_remotes(pattern)`
* `clear_remotes()`
?

This basically matches the other helpers in `desc`, e.g. for `URL`.

**Comment by hadley** [comment]
Yeah, I like it.

**Comment by gaborcsardi** [comment]
Actually, I am writing this now, and you would also need sg that updates a location, because it happens relatively often that you specify a (different) tag or hash for an existing remote. So I'll add 
* `update_remotes(remotes)`
as well. This is more work, as I need to parse the location to see which one needs to be updated.

Or maybe add_remotes should just handle this automatically, and update instead of just append.

Also, it makes sense to warn if a remote is added but the package is not in any of the dependency fields.

**Comment by gaborcsardi** [comment]
OK, I'll leave out the updating part for now, there is no proper API for it anywhere.....

**Comment by gaborcsardi** [comment]
There is an implementation in https://github.com/metacran/desc/commit/dc6d680eaf333e083dd48db1ae6fc8fe52e35eba
