### ISSUE TITLE
Installation with dependencies should first download, then install

### ISSUE THREAD

**Issue by krlmlr** [hadley/devtools#1308]
I think installation of packages + dependencies should be split in three stages:

1. Download all source packages, including their dependencies
2. Install them in the correct order
3. Apply devtools-specific post-installation steps

For 2., we can leverage `install.packages()` with a `repos` argument that points to a local path: All we need to do is to download the packages to some `contrib/src/` subdirectory and call `tools::write_PACKAGES()`. This would finally give us parallel installation with `options(Ncpus > 1)`.

It looks like this would be relatively easy to implement with the current codebase. @gaborcsardi: Do you have any plans for a separate "installer" package?

Motivation: `devtools` does *a lot* when installing packages and their dependencies, especially if these packages are from different remotes (e.g., CRAN + Bioconductor + GitHub). When revdep-checking RSQLite (with `bioconductor = TRUE`), I observed twice that I need 2-3 passes to install all revdeps. (The process is single-threaded and takes a day, I'm not too keen to repeat it *again*.)

**Comment by jimhester** [comment]
Gabor has https://github.com/MangoTheCat/remotes as a simpler option to devtools, unfortuately he started working on it right before I made a number of changes to devtools remote handling, which is why we have not switched the devtools code to use it.

I assume you are using linux, so have to recompile all of the dependencies, which is why they are taking so long to install. RSQLite only has 105 dependencies, so it should not be so onerous. This process really works best on OS X as you can download the CRAN binaries and run them in parallel. Hadley can install (and run) the (~800 or so) ggplot2 dependencies in a few hours.

**Comment by krlmlr** [comment]
The Bioconductor revdeps are still *huge*. I don't have access to a recent-enough OS X machine, but I got myself a 16-core Ubuntu server on Azure ;-)

Can you please summarize the changes you've made in "devtools" that are not yet part of "remotes" package?

**Comment by jimhester** [comment]
Biggest things were the changes in https://github.com/hadley/devtools/pull/1067, but it also doesn't have support for bioc remotes (https://github.com/hadley/devtools/pull/1194) and a number of other smaller things, basically any devtools changes from January on.

I still think splitting it out into a new package is a good idea and remotes is a great start, but it not an entirely trivial update.

**Comment by gaborcsardi** [comment]
Hi all. I don't think `remotes` is missing much that is needed for the reverse dependency checks. You don't really need updates, and I believe that it can handle bioc packages the usual way, you just specify the bioc repos.

Btw. I am also working on a separate `revdepcheck` package, based on `remotes` and `rcmdcheck`, it is private for the moment, but will make it public soon.

**Comment by krlmlr** [comment]
Thanks!
