### ISSUE TITLE
put my_unzip, system_check, etc in their own package?

### ISSUE THREAD

**Issue by rmflight** [hadley/devtools#1350]
Having issues with using the internal unzip and the arguments, saw you implemented your own version of `unzip` and `system` callers to make sure things are going ok. I think these are probably broadly useful, and was wondering if it would be useful to spin them out into their own package?

I would definitely be willing to draft such a package, but would also need input as to which functions from devtools should go there.

**Comment by hadley** [comment]
I think these will move to calling functions in @gaborcsardi micropackage. He should be able to suggest a good home for the unzip wrapper.

**Comment by gaborcsardi** [comment]
`my_unzip` is literally five lines, so that would rather be a nano-package. I would keep that in devtools. :) Unless there are some similar compress/uncompress functions, in which it would make sense to put them in some compress package. There used to sg similar on Omegahat....

`system_check` OTOH would be useful in some system package. My `processx` package is similar but quite often overkill. I have similar `safe_system` functions in  many packages, and I am sure that many people have the same.... so a `system3` package would make sense imo.

**Comment by hadley** [comment]
I'd rather have one overkill package that many smaller packages that each solve part of the problem.

**Comment by gaborcsardi** [comment]
@hadley Agreed. It's just that basically the point of `processx` is to be async, and it would basically share zero code with a simple `system3` package that just calls `system`, `system2` or `shell`, synchronously.

It think it is also a different use case, to do a quick sync call, or to start sg in the background and the manage it.

Also `processx` is much harder to implement, I am still even not sure if it is possible to implement it reliably in R code only. I tried to put it on CRAN, but it killed win-builder..... So it might be replaced with sg. containing OS specific C code in the future.

`system3` is straightforward to implement, basically the `devtools` implementation is mostly sufficient, and I already have a bunch of other similar implementations. We would just take the union of these.

**Comment by wch** [comment]
@gaborcsardi, I had a discussion with @jcheng5 today about writing some C/C++ code for process management, for the shiny testing stuff. The idea is to replace processx in the short term so that the testing can be done with a more reliable (but simpler) process management. In the long term, that code could be migrated into processx.

**Comment by gaborcsardi** [comment]
@wch Cool!
