### ISSUE TITLE
Is there (or could there be) a way to have messages displayed when using install_github()?

### ISSUE THREAD

**Issue by rpruim** [hadley/devtools#1394]
I'm wondering if it would be possible to emit a message when installing a package with `install_github()`.  I'm thinking messages that alert users to things like:

  * the status of the package (stability/danger level, etc.)
  * the existence of other branches that might be used with `ref = `
  * perhaps an intended timeline for moving to CRAN
  * etc.

**Comment by jimhester** [comment]
Listing branches available could be useful, but belongs in a separate function rather than output by `install_github()`, which arguably produces too much output as it is. 

The remaining information has no standard location or definition and often the package authors do not know the answers themselves, so don't see how it would be possible for devtools to provide.

**Comment by jennybc** [comment]
It would be interesting if the stuff people put in the usual badges was actually machine readable. It's so close already.

**Comment by hadley** [comment]
I think this is out of scope for devtools just because we have so many more pressing problems. I think some standard for badging in-development packages is a good idea though.

**Comment by jennybc** [comment]
I have used <http://www.repostatus.org> badges to annotate stuff that is not yet on CRAN or might never to go CRAN. The idea also seems useful at the other of the life cycle.
