### ISSUE TITLE
devtools' system.file() breaks citation()

### ISSUE THREAD

**Issue by cosi1** [hadley/devtools#1404]
Hello,

When I ran unit tests for my package (with testthat), the tests crashed on the `citation("my_package_name")` function referenced in one of the modules, with an error message:

> $ operator is invalid for atomic vectors

and an additional warning:

> no package 'my_package_name' was found

I investigated it and it seems that the following code in `citation()` is the problem:

    dir <- system.file(package = package, lib.loc = lib.loc)
    # ...
    meta <- packageDescription(pkg = package, lib.loc = dirname(dir))
 
When a test is run, `system.file()` (overwritten by devtools) points to the `inst/` directory in the source location of the package, which is what `packageDescription()` can't handle, yielding NA and a warning message.

I don't know if this is a fault of devtools, testthat or R's base, but definitely it's an annoying bug rendering unit tests useless in this specific case.

Best regards,
Paweł

**Comment by jdblischak** [comment]
I have another example where this causes problems with unit tests. I created an rmarkdown template in `inst/rmarkdown/templates`. My unit tests break because `rmarkdown::draft` calls `system.file`, which then searches my source code instead of the installed package. Because of the differences in directory structure, this breaks the tests.

I understand that this behavior was purposeful (e.g. [this comment](https://github.com/hadley/devtools/issues/740#issuecomment-78640868)), but it would be useful if there was some way to temporarily disable the shims. I tried experimenting with including `detach("devtools_shims")` in my unit test, but that did not work. For now, I am skipping these tests with `skip` and running them manually via `source`.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

FWIW I don't think your explanation of the cause is correct because the shims are attached close to the global environment; they affect user code, not code in packages.

**Comment by cosi1** [comment]
Mine doesn't seem to be associated directly with devtools' `system.file()`, but rather with the corrupt handling of package directories in `packageDescription()`.

Steps to reproduce:

1. Create package `myPackage` in a "simulated SVN repository", e.g., ~/myPackage/trunk. (Note: this works for any directory name different than the actual name of the package.)
2. Enter that directory: `setwd("~/myPackage/trunk")`
3. Load devtools: `library(devtools)`
4. Load `myPackage` with devtools: `load_all()`
5. Try to get citation for your package: `citation("myPackage")`

The reason `citation()` fails is because `packageDescription()` assumes that the root directory of a package would be the same as its name, which is not always true. Anyway, the above example works when `system.file()` isn't masked by devtools.

**Comment by hadley** [comment]
Ah so `citation()` only fails if you've run `load_all()`. That seems like a sufficiently rare case that I'm just going to say "don't do that". I'd be happy to review a PR if anyone figures out a fix, but otherwise it's sufficiently low-priority that it's unlikely to be fixed otherwise.

**Comment by kiwiroy** [comment]
Is this the cause in this [reprex](https://github.com/kiwiroy/ReprexDevtools)? Is there a solution?

**Comment by jimhester** [comment]
Yes, `devtools::test()` uses `devtools::load_all()`, which breaks `citation()`. The tests should work fine with `devtools::check()` which runs `R CMD check` and does not use `load_all()`.

**Comment by kiwiroy** [comment]
Thanks for the confirmation @jimhester.

`devtools::load_all()` is responsible for ending at this [point](https://github.com/r-lib/usethis/blob/59b083779c142242ed5291242b72f41822996000/R/helpers.R#L63-L67).

So this is a [workaround](https://github.com/kiwiroy/ReprexDevtools/compare/workaround) using `pkgload` `:::` internals and both ⌘ ⇧ T and ⌘ ⇧ E succeed, which saves a full check.

Is this the responsibility of `usethis` and its [`.onLoad()`](https://github.com/r-lib/usethis/blob/1d0c797cdd5a6681dced8ec3e0e6d18688cb760a/R/usethis-package.R#L5)?
