### ISSUE TITLE
Installing rgl from rforge/rgl/pkg/rgl requires SVN - but it shouldn't?

### ISSUE THREAD

**Issue by MikeWise2718** [hadley/devtools#1423]
I tried to install rgl from the rforge mirror rforge/rgl as suggested in this post (by one of the rgl contributors I believe). [http://stackoverflow.com/questions/37142762/how-do-i-install-the-latest-version-of-rgl/37142971#comment69764517_37142971](url) with the command `devtools::install_github("rforge/rgl",subdir="pkg/rgl")`

Since it was suggested there I believe it probably worked at one time, however now it fails with the message:
```
> devtools::install_github("rforge/rgl",subdir="pkg/rgl")
Downloading GitHub repo rforge/rgl@master
from URL https://api.github.com/repos/rforge/rgl/zipball/master
Installing rgl
Error: SVN does not seem to be installed on your system.
```

Since the url plus subdir point at a perfectly good (though possibly out of data) rgl package, it really should not have require SVN, right?

So I think this is a bug...

**Comment by jimhester** [comment]
rgl is using the devtools `Remote:` feature to install a remote dependency using SVN, `https://github.com/rforge/rgl/blob/master/pkg/rgl/DESCRIPTION#L20`, which does need SVN to be installed.

However there does still seem to be a bug here, I get the following (with svn installed)

```r
devtools::install_github("rforge/rgl/pkg/rgl")
#> Downloading GitHub repo rforge/rgl@master
#> from URL https://api.github.com/repos/rforge/rgl/zipball/master
#> Installing rgl
#> svn: warning: W160013: File not found: revision 1528, path '/pkg/rglwidget/trunk/DESCRIPTION'
#> svn: E200009: Could not cat all targets because some targets don't exist
#> svn: E200009: Illegal target for the requested operation
#> Error: There was a problem retrieving the current SVN revision
```

**Comment by MikeWise2718** [comment]
But I downloaded the repo and installed with `install.packages("rgl",type="source")` from the `pkg/rgl` directory and it installed ok (I think, the version number was off which prevented me from doing a lot of testing). And I do not have SVN installed. I think it is not meant to need SVN.

**Comment by gaborcsardi** [comment]
@jimhester I believe that `devtools` assumes too much about the SVN directory structure. AFAICT this is the same issue that was fixed in `remotes` not too long ago: https://github.com/r-pkgs/remotes/pull/33

@MikeWise2718 `install.packages()` does not use `Remotes`, so it does not try to install the dependency from SVN. But I guess the package author put the `Remotes` dependency there for a reason.

**Comment by MikeWise2718** [comment]
You mean there is a `remotes` dependency in `install_github` or one in `rgl`. Sorry, I am not familiar with what `remotes` does (`Remotes`?) and how it works.

**Comment by gaborcsardi** [comment]
@MikeWise2718 

The R-forge version of `rgl` has a `Remotes` field in its `DESCRIPTION` file, meaning that it requires some (dev version) of some package that is not available from CRAN, but needs to be installed from SVN. That's why the installation needs SVN. There is nothing broken in `devtools` in this respect.

What @jimhester  says, is that even if you have SVN installed, it will fail, because there is another bug in `devtools`. This bug was fixed in the `remotes` package, which is an alternative to (and mostly a copy of) `devtools::install_github()`. 

So what you can do is to
* Install SVN, and then
* Use the `remotes` package to install `rgl` from R-forge, or wait until devtools is fixed.

**Comment by MikeWise2718** [comment]
Ok, so the `rgl` that `install.packages` built might not have everything that was intended, i.e. it might be want to have some packages with functionality that it expects, regardless of the fact that it did compile.

**Comment by gaborcsardi** [comment]
@MikeWise2718 Exactly. You would need to ask the `rgl` authors or try to look in the commit messages or NEWS file to see what exactly is wrong with the CRAN version of the dependency.

**Comment by jimhester** [comment]
This should be fixed after https://github.com/hadley/devtools/pull/1424, based on the PR Gábor mentioned.
