### ISSUE TITLE
run_examples() doesn't always respect run

### ISSUE THREAD

**Issue by bdwyer2** [hadley/devtools#1454]
When the `fresh` argument is `TRUE` the value of `run` seems to have no impact
```
run_examples(pkg = ".", run = FALSE, fresh = TRUE)
```

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by bdwyer2** [comment]
I think it would be difficult to create a reproducible example because I would have to create a whole package skeleton but it's easy to see the bug if you run `View(devtools::run_examples)` and look at lines 20-29.

**Comment by hadley** [comment]
Maybe you'd like to do a PR instead?

**Comment by hadley** [comment]
@Neil-Schneider I think you did the PR on the wrong repo.

**Comment by hadley** [comment]
Oh I see you did it in the right place and @jimhester merged it

**Comment by Neil-Schneider** [comment]
Yes he did. Thanks!
