### ISSUE TITLE
load_all() and test() don't load package dependencies?

### ISSUE THREAD

**Issue by fruce-ki** [hadley/devtools#1472]
Please see issues linked below.

https://github.com/Rdatatable/data.table/issues/2023
https://github.com/Rdatatable/data.table/issues/2053

It seems that `test()` and `load_all()` and possibly others have recently changed behaviour with regards to resolving imported packages, at least with regards to the 'data.table' package.

Testing of perfectly valid code should not fail like that.

**Comment by hadley** [comment]
data.table uses some magic to determine if it's needed or not. Clearly the magic is failing due to the special way that `load_all()` simulates package loading.  

I'd recommend filing a minimal reproducible example at [pkgbuild](https://github.com/r-lib/pkgbuild), which is where the package loading code now lives. You'll probably need to create a minimal package that illustrates the problem and host it on github.

**Comment by hadley** [comment]
Sorry, I meant pkgload, not pkgbuild
