### ISSUE TITLE
Feature request: build some but not all vignettes

### ISSUE THREAD

**Issue by Hong-Revo** [hadley/devtools#1567]
It would be nice to have an argument to `build_vignettes` that lets you choose specific vignettes to build.

My specific use case is that I have 3 vignettes for my package. One of them requires a Spark connection, and takes several minutes to build. The others don't require Spark, and are likely to error out if it's present, in fact.

My current workaround for building the Spark vignette is to move the other 2 vignettes out of the /vignettes subdir, run `build_vignettes()`, and then move them back again. I do the same in reverse if I want to build the non-Spark vignettes. This isn't very automated, and prone to errors.

Something like `build_vignettes(pattern="regex")` would solve this nicely, where only files matching the supplied regex are built.

**Comment by jennybc** [comment]
You might be better off to conditionally execute the code in that vignette based on, say, an env var that you set when conditions are favorable. Put something like this in a setup chunk:

``` r
SPARK <- identical(tolower(Sys.getenv("SPARK")), "true")
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  purl = SPARK,
  eval = SPARK
)
```

**Comment by Hong-Revo** [comment]
Unfortunately that doesn't work. The vignette still gets compiled, it just means that there's no output from any R code inside it. It then gets copied to inst/doc, overwriting the version with the output.

**Comment by jennybc** [comment]
True. Is this package already on CRAN or destined for that? I find the entire workflow around vignettes painful if they have special requirements and shouldn't be rebuilt casually. There are various workarounds in order to "pre-compile" vignettes, so you may need to go that route. Even if `build_vignettes()` became more flexible, it won't solve the problem re: CRAN.

If you think you might make a package website with [pkgdown](http://hadley.github.io/pkgdown/), you could turn this spark vignette into a non-vignette article and wash your hands of the problem. That is what I plan to do from now on for vignettes that require auth tokens, for example.

**Comment by hadley** [comment]
I think resolving this issue is outside the scope of `build_vignettes()`. I agree that is a frustrating problem, but I don't think manually building vignettes locally is the way forward.

**Comment by Hong-Revo** [comment]
Will pkgdown actually solve this problem? From what I saw on browsing the documentation, the situation is the same: `build_site` will build all vignettes, without any options to choose which ones.
