### ISSUE TITLE
Chicken-and-egg NAMESPACE problem with Roxygen2, `devtools::check()`, and Rcpp

### ISSUE THREAD

**Issue by dbaston** [hadley/devtools#1599]
Running `devtools::check()` on a project that uses Rcpp fails if the `NAMESPACE` file does not exist:

```
> devtools::check()
Updating wsim.lsm documentation
Loading wsim.lsm
Error in Rcpp::compileAttributes() : 
  pkgdir must refer to the directory containing an R package

```

To generate the `NAMESPACE` file, I need to run `devtools::document()`.  But this also invokes Rcpp, which in turn fails because the `NAMESPACE` file does not exist:

```
> devtools::document()
Updating wsim.lsm documentation
Loading wsim.lsm
Error in Rcpp::compileAttributes() : 
  pkgdir must refer to the directory containing an R package
```

It's not enough to run `touch NAMESPACE` before build, because Roxygen2 will only replace a NAMESPACE file that it generated.  For now, I papered this over with a hackish Makefile:

```
NAMESPACE:
	echo "# Generated by roxygen2: do not edit by hand" > NAMESPACE

check: NAMESPACE
	Rscript -e "devtools::check()"

```

But I wonder if devtools could take care of this somehow?  Since `NAMESPACE` is autogenerated by Roxygen2, I don't want to commit it to the repository.

**Comment by jimhester** [comment]
I should just commit the NAMESPACE file, not doing so makes it more difficult for others to install your package without any real material gain.

**Comment by wch** [comment]
There are pros and cons of committing generated files to a repository. The stance taken in devtools is that the files in the repo can be given to `R CMD build` to create a source or binary R package. This means that some generated files, like NAMESPACE file and the .Rd files, are part of the repository. Others, like .so and .dll files, are not, because they are created during the build phase.

Another reason for having those files be committed to the repository is so that when a version that has been released to CRAN is tagged, that tag represents the set of files that was used to create the source package that was submitted to CRAN. If the NAMESPACE and .Rd files are not part of the repository, there's no guarantee that they'll be the same when you generate them in the future, because roxygen2 may behave differently, and because the .Rd files might inherit information from other packages, and the other packages can change.
