### ISSUE TITLE
Full GPL license

### ISSUE THREAD

**Issue by privefl** [hadley/devtools#1601]
When trying to submit one of my packages to CRAN, I got the following message:

> Please do not provide a full copy of the GPL but only use the LICENSE file for specifying any possible restrictions.

Is this a new CRAN restriction? 
If it is, it would be useful to modify the behaviour of `devtools::use_gpl3_license()`.

**Comment by jimhester** [comment]
This behavior is fixed in [usethis](https://github.com/r-lib/usethis), which is what **devtools** will be using for this function in the future.

In the meantime I would suggest renaming your `LICENSE` file to `LICENSE.md` and adding it to `.Rbuildignore`, so it is not included in the built package. This will allow you to continue to have the license file in your source repository but not be against the CRAN guidelines.
