### ISSUE TITLE
Clarification re: usethis functions

### ISSUE THREAD

**Issue by jennybc** [hadley/devtools#1698]
The Diaspora section of the README says:

> Generally, you should not need to worry about these different packages, because devtools installs them all automatically.

But I also see that infrastructure functions have been deprecated here:

https://github.com/hadley/devtools/blob/master/R/infrastructure.R

So ... what is the recommended way to call these functions going forward? For people who attach workflow packages in, e.g., `.Rprofile` is there a recommended practice re: which ones to attach and in which order?

cc @maelle

**Comment by jimhester** [comment]
Unfortunately for the very near term CRAN **devtools** does not have the **usethis** functions, and we cannot update devtools / the diaspora packages because devel **processx** is blocked on CRAN. So if you are using CRAN **devtools** you might want to attach **usethis** after **devtools**. 

Devel devtools attaches **usethis** when you attach devtools (before devtools in the search path), so if you

```r
library(devtools)
use_test("foo")
```

R calls `usethis::use_test()` directly. The only time you will get the devtools implementation (and the deprecration notice) is if you use `devtools::use_test()`. We did it this way because we want package authors to depend on the various diaspora package directly rather than depending on all of devtools, but we want users to just have to attach **devtools**.

Eventually the deprecration message (and devtools `use_()` functions) will be completely removed and devtools will put **usethis** in `Depends:`.

The main idea is the only package end users should ever need to attach anywhere is **devtools**.

**Comment by jennybc** [comment]
Thanks. I'm glad I asked!
