### ISSUE TITLE
request: --as-cran to include title case test

### ISSUE THREAD

**Issue by msberends** [hadley/devtools#1702]
From my submission of today, which had 0 errors, 0 warnings and 0 notes in RStudio when checking with devtools:
```
Thanks, we see:


The Title field should be in title case, current version then in title case:
'Shiny App for Line By Line Comparison of Two Files'
'Shiny App for Line by Line Comparison of Two Files'

Please fix and resubmit.

Best,
Uwe Ligges
```

So I made a small mistake; title case not applied. Would it be possible to include this in the Check Package function when the `--as-cran` parameter is used? Thanks!

**Comment by jimhester** [comment]
This check is _not_ run by default with `devtools::check()` because the check require network access to CRANs servers and take a long time to run.

Using `devtools::check(check_version = TRUE)` turns on this check, and this check is turned on when using `devtools::release()`. It will also be turned on if you submit your package to win builder with `devtools::build_win()` or rhub with `rhub::check_for_cran()`.

These are all checks that are useful to run prior to CRAN submission.

**Comment by msberends** [comment]
Ah thanks 👍

**Comment by jimhester** [comment]
I made a change in the devel version of devtools which will now turn on more of the incoming checks, so this specific case will now be caught by `devtools::check()` with the default arguments.
