### ISSUE TITLE
devtools::bootstrap()

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#592]
Need some way to help people make sure they're up to date

* is R version current?
* is RStudio version current?
* is devtools up-to-date?

Need to deal with windows issues.

**Comment by hadley** [comment]
@gaborcsardi can you please remind me of your package that checks R is up-to-date?

**Comment by hadley** [comment]
@gaborcsardi (I mean that returns the released version of R)

**Comment by hadley** [comment]
@gaborcsardi oh it's rversions - I was looking under your person github instead of metacran.

**Comment by gaborcsardi** [comment]
@hadley Yes, it is also on CRAN now: http://cran.r-project.org/web/packages/rversions/index.html This queries the SVN, so it is not super fast.

I also have a web service, which just serves static data in JSON, it is updated after each R release:
http://rversions.r-pkg.org/r-release
http://rversions.r-pkg.org/r-oldrel
http://rversions.r-pkg.org/r-versions
This is fast, obviously.

**Comment by hadley** [comment]
Is there a reason you don't use that in rversions? I don't care much about speed for this usage - I'd rather have something that's likely to keep working for a few years.

**Comment by gaborcsardi** [comment]
You mean for not using my web service in the R package?

The R package was before and it is used to update the web service. I made the web service after, because I needed the current version without R, in https://github.com/metacran/r-builder, to check which version of R to install.

But I could use the web service in the R package by default, obviously. I am not sure if that's better or not.

**Comment by hadley** [comment]
@gaborcsardi ah, makes sense.

**Comment by gaborcsardi** [comment]
It is actually pretty slow (1s vs ~0s), so I think I might change it to use the web service by default.
