### ISSUE TITLE
git_doctor/github_dr

### ISSUE THREAD

**Issue by hadley** [hadley/devtools#643]
Check that you're set up to use git/github:

* Git is installed
* Have ssh key
* Have set username and email globally
* Have github pat token available

**Comment by hadley** [comment]
@jennybc do you have any code that helps check students are set up correctly to use github? Can you suggest any thing else I should be checking in this function?

**Comment by jennybc** [comment]
All the checks I've ever done have been interactive. FWIW here they are anyway:

We run `git config --global --list`, which allows sanity check of `user.name`, `user.email`, and `credential.helper`. Note that I usually have students work with GitHub via https, at least at first, rather than fussing with the ssh keys. This requires a credential helper, so we use `git --version` to make sure it's 1.7.10 or newer. The [advice on activating and initializing the credential helper](http://stat545-ubc.github.io/git06_credential-caching.html#turn-on-the-credential-helper) varies by OS and I'm not sure if you even want to get into that.

I think it's great for `devtools` to do a Git check-up! Other thoughts:

  * I've never used [git2r](https://github.com/ropensci/git2r) but the `cred_*()` functions might be relevant to your support of ssh.
  * Telling user where Git lives is a useful thing, because sometimes they need to tell RStudio this explicitly: `which git` (*nix), `where git` (some Windows), `whereis git.exe` (some other Windows).
  * Checking that the Git executable is in `PATH` would also be a huge favour for novices.

**Comment by hadley** [comment]
git2r has come a long way since I last looked at it - I think I might be able to replace a lot of code.

**Comment by hadley** [comment]
@jennybc I decided not to implement the path checking - RStudio also makes some efforts to determine the correct git path, and I don't want to have to replicate exactly what it does. I think in the long run, it might be possible for RStudio to also switch to using git2r, thus avoiding the path problem altogether.
