### ISSUE TITLE
devtools should import roxygen2

### ISSUE THREAD

**Issue by wch** [hadley/devtools#690]
Because it uses `roxygen2::document()` extensively.

**Comment by Geoff99** [comment]
I'm very much a novice, and largely a spectator/learner rather than a contributor, but for what It's worth, I agree, especially if pull request #649 (or a variant thereof) is accepted to fix an issue with load_all and S4 classes (basically insert a call to `roxygen2::update_collate()` into `load_all` to ensure the collate order is up to date so that S4 classes with inheritance split across several .r files are loaded in the intended order).  That would make roxygen2 essential for (yet) another core function of devtools.

**Comment by Geoff99** [comment]
PS : The following is perhaps a bit esoteric, but the behaviour had me puzzled for quite a while, so I'll mention it in case it help others avoid the pitfall I encountered, while I was experimenting with forked copies of devtools and roxygen2.

##### If you want the version of roxygen2 to be checked when devtools is loaded, you have to ...

(Even) if you have devtools import roxygen2, the version of roxygen2 specified in the DESCRIPTION file will *not* necessarily be checked automatically (as at R version 3.1.2) when devtools is loaded if you use the `roxygen2::some_roxygen2_function` syntax.

If you want the version of roxygen2 to be checked you have to either:
  * Continue to explicitly check it in the devtools code using  `requireNamespace("roxygen2", versioncheck = list(op = ">=", version = "x.y.z"))` i.e the same as you would while roxygen2 is a Suggests dependency,  *or*
  *  Either
      - `@import roxygen2` or
      -  `@importFrom roxygen2 at_least_one_roxygen2_function`

This is because `loadNamespace`  reads the version constraints on Imports package dependencies (eg roxygen2) when it processes the DESCRIPTION file for the package it is loading (eg devtools),
**but**
 it does not check the version constraints until it is processing the NAMESPACE file.  

If you have used the `devtools::some_function` syntax throughout devtools (ie you do not mention roxygen2 in an `@import` or an `@importFrom` ) there will be no mention of  roxygen2 in the NAMESPACE file, and hence no version checking will be done.

PPS It is possible that using `library(devtools)` (which is what most users are likely to do) gets around this, because `library` does some extra version checking of its own (I think - I haven't worked through this closely)

PPPS As at R 3.1.2 you actually have to use `requireNamespace("roxygen2", versioncheck = list(name = "roxygen2", op = ">=", version = "x.y.z"))`, because there is a discrepancy between the documentation for `loadNamespace` (and `requireNamespace`) and the actual code - but I understand this will be fixed in a future release of R
