### ISSUE TITLE
create(): Authors@R in DESCRIPTION should call person()

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/devtools#693]
Just because `R CMD check` will check for this now: https://github.com/wch/r-source/commit/25d7384212d9c0123984b3f5e3d37acd2607b1f6

Seems trivial, and I can send a PR, if you want.

**Comment by hadley** [comment]
I think we need to push back on this a little. `R CMD check` should be checking that the result of the expression is a person object (or coercing to it), not looking at the literal calls.

**Comment by hadley** [comment]
They're definitely not going to change :(

**Comment by gaborcsardi** [comment]
That's sad, but not completely unexpected.

Btw. I think R/devtools would very much need a build system that runs before `R CMD build`. This would solve (well, work around) this problem, and could also run roxygen, the Rcpp attributes generator, etc. I have to say I hate putting generated files into the repo....

**Comment by hadley** [comment]
Fixed in 1650b1ffed12b8d8348eec9ba22c8d962a01d98e

**Comment by hadley** [comment]
I have to say I'm getting more and more comfortable about putting generated files in the repo, just because R users are not like typical software developers.  There are many advantages to including generated files when most people installing/building your package are using it, not developing it.

**Comment by gaborcsardi** [comment]
:) Well, you can get used to bad habits as well, and then they don't seem so bad any more.

With a simple build system, you could have both. Almost all people already have roxygen installed anyway, and Rcpp as well. `install()` would just run a simple script, automatically, to build the docs, and whatever we would like add later. So it would be just us user friendly as it is now, in fact the users would not notice anything (well, a bit longer install time and more output).

E.g. it is kind of annoying when people use different versions of roxygen for different projects, and then it keeps overwriting the headers of the manual files, unless you undo it by hand....

It is true that it increases complexity, and ideally this should be part of `R CMD build`, anyway.

**Comment by hadley** [comment]
Most people _do not_ have a working C compiler because they're on windows. Even installing Rtools is challenging for many people. If you only talk to other R programmers/developers, you start to think that getting a working R tool chain is easy, but it's not for most R users.

Writing the roxygen version into the headers is actually a very deliberate way of making sure everyone is using the same version of roxygen so that spurious differences don't accidentally get bundled into a commit.

**Comment by gaborcsardi** [comment]
Yes, I keep forgetting that you need to a C compiler to use roxygen. (I worked around it in my own packages.)

> Writing the roxygen version into the headers is actually a very deliberate way of making sure everyone is using the same version of roxygen so that spurious differences don't accidentally get bundled into a commit.

Yes, although this solves a problem that you created by using github both for version control and distribution. But, indeed, this is convenient for users.

**Comment by hadley** [comment]
There's also the data analysis side of R, where I think it really makes sense to check in generated files (i.e. your data analysis reports from knitr), because it makes it much easier to track changes in the result. 

Plus what's the harm in committing generated files, provided you have a standard, documented way of re-generating them?

**Comment by gaborcsardi** [comment]
In general, these files bloat the repository.

More specifically:
 - it is considered good practice not to check in generated files (yes, this is a very week point, I agree)
 - they mess up `git diff`, and the history in general
 - they (might) mess up merging and rebase
 - as said above you need to be on the same roxygen version as other devs, and this sometimes changes between projects. (In the past, for a while I always had to re-install roxygen for this, many times a day.)
 
But I agree with you that the benefits are bigger for R packages, I just forgot about the C compiler.

Btw. how about working around in roxygen, so that it does not compile the C source (only if it is really needed). IMO, it is not needed for most packages.

**Comment by hadley** [comment]
My responses

1. That's not an argument ;)
2. That's in the eye of the beholder - I'd claim in many situations they actually enhance `git diff` because you can see exactly what's changed in the _output_
3. Rebase, maybe, but lots of people consider that bad practice. Merge, not really, because you can always regenerate the files.
4. Yes, that's a pain, but should be solved with packrat or similar (eventually)

**Comment by wch** [comment]
There are four different stages of package building:

1. "True" sources (no generated files)
2. True sources plus generated files. This can be given to `R CMD build`. It can also be installed with `devtools::install`.
3. An R source package. This can be installed with `R CMD install` or `install.packages(type = "source")`.
4. An R binary package. This can be installed with `R CMD install` or `install.packages()`.

The devtools workflow is to check in stage 2 to the repo, but @gaborcsardi, you (and others) would like to check in stage 1.

Maybe someone (you?) could outline a workflow for that? I suspect that in order to get from stage 1 to 2 in a repeatable manner, another file with build metadata (e.g., versions of other packages to build with) would be needed. Perhaps an automated build system would be useful - when a stage 1 commit is checked in, you could build a stage 2 package and push it on a branch or maybe a different repo. If there is code to do all this, it might belong in a separate package.

**Comment by gaborcsardi** [comment]
First of all, I agree with @hadley, that unless we manage to change roxygen to work without a C compiler (well, almost always), the current way of putting the generated man files into repo is the best compromise.

Second, I still think that bloating the repo with generated files is not a good idea. The number of things you will want to auto-generate in the future is only increasing:
- NAMESPACE, DESCRIPTION
- manual
- vignettes
- R/C/C++ code for automatically wrapping C/C++ libs
- embedded libraries, like libgit in `git2r`
- JS/npm packages for the new V8 engine.
- etc.

Third, and I am repeating myself again, the root of all "troubles" is that we are using the _same_ Github repo for development and distribution.

@wch 
> Maybe someone (you?) could outline a workflow for that?

Well, not really yet, sorry. I had some ideas when I brought this up earlier today, but now realized that the good solution is to really separate development from distribution. But this is also not easy, because it complicates the workflow, and makes it much more error-prone.

You are probably right that this all belongs to a separate package/tool.
