### ISSUE TITLE
Can install_bitbucket use the ssh public key for authentication when install from a private bitbucket repository?

### ISSUE THREAD

**Issue by imadcat** [hadley/devtools#713]
It seems to be a much safer practice to rely on public key than to pass the *username* and *password* parameters in clear text.

**Comment by hadley** [comment]
I'd be happy to review a pull request that implemented this, but since I don't use bitbucket, I can't write it myself.

**Comment by Serenthia** [comment]
I'm not really wanting to commit my plaintext Bitbucket password for all my company to see, but I'm not sure of any way round this without this feature?  I'd like to second @imadcat's request, should anyone feel up to the task of making that PR.

Many thanks

**Comment by kleinschmidt** [comment]
I was hoping to do the same thing. Once I looked at the code, however, I realized that `install_bitbucket` uses the REST API to download a .zip of the repo. The API can only be accessed through HTTPS (as far as I can tell).

The way around it is to use `install_git('git@bitbucket.org/<username>/<repo>/')` instead of `install_bitbucket('username/repo')`, but that requires a bit more boilerplate. @hadley, would you be open to falling back on `install_git` for something like `install_bitbucket('<username>/<repo>', use_ssh=TRUE)`? If so I'll open a PR.

**Comment by imanuelcostigan** [comment]
See #1220

**Comment by paul4forest** [comment]
See also  bitbucket [app passwords](https://bitbucket.org/account/admin/app-passwords)
> in the Access Management section of your account settings
As seen on [App passwords are here in Bitbucket Cloud](https://blog.bitbucket.org/2016/06/06/app-passwords-bitbucket-cloud/?utm_source=twitter&utm_medium=social&utm_campaign=bitbucket_app_passwords).
