### ISSUE TITLE
devtools::system.file and base::system.file do not behave the same

### ISSUE THREAD

**Issue by lucacerone** [hadley/devtools#740]
devtools::system.file(package="pkg_under_development")

returns 

pkg/dev/path/inst (inst folder whose content will be copied recursively)

behaves differently than base::system.file("pkg_under_development")

that would return

pkg/inst/path   (root of the package)

Using an empty string is one way to detect the installation folder of a package in base R ;
for consistency devtools::system.file should return the root of the folder when no parameters or an empty string are passed for the files.

**Comment by wch** [comment]
The reason it returns `inst/` is because that's where files that `system.file()` looks for are most likely to be.   For example, if someone does `file.path(system.file(package="foo"), "myfile")`, the current method works better.

The directory structure of an in-development package is different from the directory structure of an installed package, and we decided this was the best heuristic to use.

See the source for more info: https://github.com/hadley/devtools/blob/master/R/shims.r#L27-L96

**Comment by wch** [comment]
To clarify a bit: files from `inst/` in the package sources get copied to the top level of the installed package, and that's why `shim_system.file()` returns the `inst/` directory by default.

**Comment by lucacerone** [comment]
Thanks @hadley and @wch. I agree absolutely that it should prefix `inst` to  simulate the behaviour of the `base::system.file` when you have to access a file that is in `inst` and it will be copied to the root later. My point is that it can resemble even more the `base` one by checking whether `as.list(...)` is an empty list, or it contains only an empty character, and in that case just return pkg_path before prefixing inst and doing all the next steps.

Reading the code (thanks I wasn't able to find it), it doesn't look like this would break existing functionalities, but I might be wrong of course. I could try to do it myself and push a pull request, but if you prefer to keep it this way I understand :+1: 

Thanks a lot for all the clarifications!
