### ISSUE TITLE
R development version and devtools::release() Error in git2r::status(r, verbose = FALSE) :    unused argument (verbose = FALSE)

### ISSUE THREAD

**Issue by jwb133** [hadley/devtools#797]
Following the CRAN Repository Policy, I've installed the current development version of R ((2015-05-10 r68348) -- "Unsuffered Consequences"), before submitting my package to CRAN. However, upon doing so, when I run devtools::release() I receive an error:
Error in git2r::status(r, verbose = FALSE) : 
  unused argument (verbose = FALSE)

Switching RStudio back to R-3.2.0 (current release version), I do not obtain the error. I'm assuming I should follow the CRAN Policy, and so am wary of devtools:release() ing using the release rather than development version.

Many thanks!
Jonathan

**Comment by hadley** [comment]
Maybe you need the dev version of git2r?  

But I don't usually bother with installing R-devel myself - `build_win()` tests on R-devel for you.

**Comment by rpruim** [comment]
Actually, I think the problem is the other way around -- you need to have an OLD version of `git2r`.  Looks like the `verbose` argument to `git2r::status()` was [recently removed (at @hadley's suggestion)](https://github.com/ropensci/git2r/issues/125).  The change is not backward compitable and now using `verbose = FALSE` produces and error.

I get this same error using R 3.2.0 using both CRAN and github versions of `git2r` with both CRAN and github versions of `devtools`:

```r
> devtools::release()
Error in git2r::status(r, verbose = FALSE) : 
  unused argument (verbose = FALSE)
> traceback()
4: git2r::status(r, verbose = FALSE)
3: vapply(git2r::status(r, verbose = FALSE), length, integer(1))
2: git_uncommitted(pkg$path)
1: devtools::release()
> args(git2r::status)
function (repo, staged = TRUE, unstaged = TRUE, untracked = TRUE, 
    ignored = FALSE) 
NULL
```
But if we roll back a couple weeks to
```r
install_github("ropensci/git2r", ref="66e1523872b5edeaf1c4fd2b753fd99e305994d1")
```
then we get an out-of-date warning, but things go through:
```r
> devtools::release()
Warning: DR_DEVTOOLS FOUND PROBLEMS
* Devtools or dependencies out of date: git2r
```
Unfortunately, `git2r` was just submitted to CRAN, so it is a little late to get the backward compatibility and just have it ignore `verbose = FALSE`.

**Comment by hadley** [comment]
Oh bummer. I guess I'll need to do a point release in the near future

**Comment by LechMadeyski** [comment]
Using R3.2.0 and the latest dev version of devtools (and git2r) if you run `devtools::release()` you get:
Warning: Uncommited changes in git.
Error in git2r::lookup(r, git2r::branch_target(upstream)) : 
  error in evaluating the argument 'sha' in selecting a method for function 'lookup': Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘branch_target’ for signature ‘"NULL"’
