### ISSUE TITLE
Packaged don't find vignettes created with use-vignette

### ISSUE THREAD

**Issue by smach** [hadley/devtools#931]
Packages don't "find" vignettes created with use-vignette() -- that is, they're not listed in the package help or when runningvignette() and browseVignettes() -- without also running build_vignette(). Issue filed per this Twitter thread https://twitter.com/sharon000/status/644256000451694592

**Comment by jennybc** [comment]
What IS the official party line on how to manage vignettes during development?

In your book, [vignette workflow](http://r-pkgs.had.co.nz/vignettes.html#vignette-workflow) addresses the (ephemeral) preview. And [development cycle](http://r-pkgs.had.co.nz/vignettes.html#vignette-workflow-2) gets at the other end ... when building and installing a package properly.

What about the bit in the middle?

**Comment by hadley** [comment]
I preview them with Cmd + Shift + K. What else do you need to do during dev?

**Comment by jennybc** [comment]
I'm thinking about the vignettes relative to what we do for roxygen comment / Rd file (and README.Rmd / README.md?).

The [documentation workflow](http://r-pkgs.had.co.nz/man.html#man-workflow) results in persistent help files you can preview in their natural habitat with `?`. What's the equivalent for a vignette? The Cmd + Shift + K preview can be a drag because sometimes they take a long time to render.

It's not that I can't figure out how get a rendered vignette. It's about figuring out the most `devtools`-ish way to get and possibly hold on to them.

**Comment by hadley** [comment]
Oh hmmmm, maybe we need a `vignette()` shim to get the dev version?

**Comment by hadley** [comment]
Moved to pkgload
