### ISSUE TITLE
A use_news() function

### ISSUE THREAD

**Issue by stephlocke** [hadley/devtools#957]
It would be very handy if there was a function that created the NEWS file, and ideally contained a "best practice" example

Apologies if this has already been requested and declined, could only find #105

**Comment by gaborcsardi** [comment]
It is imo unclear what the best practice is. 

* Traditionally R packages used a NEWS.rd file, but this is heavy, and cumbersome, so a lot of people don't use them any more.
* On GitHub people use NEWS.md files, these are in Markdown. This is used now by CRAN as well, see below.
* You can also use a NEWS file, according to the GNU standards. This is picked up and shown on CRAN, as a text file, AFAIR.

Personally I like NEWS.md. In fact recently (https://github.com/wch/r-source/commit/e7cf1f06c0cdf439eca9d561b84316a44089e142) NEWS.md is picked up by CRAN. Incidentally inst/NEWS.md is also picked up, which is a pity, because I specifically put NEWs.md in inst/ so that CRAN does not bother with them....

CRAN uses Pandoc to format Markdown, which is unfortunate, because GitHub uses a different parser, and you often end up with an MD file that is fine on GitHub, but gives warnings or errors on CRAN. And then you get emails from CRAN.

**Comment by gaborcsardi** [comment]
Btw. here is a recent discussion about NEWS.md: http://r.789695.n4.nabble.com/NEWS-md-support-on-CRAN-td4707539.html

**Comment by stephlocke** [comment]
The *current* way in the R Extensions manual is NEWS so we can start with that first? We can  then converge on markdown as the R versions move towards it.

**Comment by hadley** [comment]
I only use `NEWS.md`, so I'd want that for devtools.

**Comment by hadley** [comment]
@gaborcsardi have there been any updates to `NEWS.md` support for CRAN? IIRC it still causes a R CMD check problem.

**Comment by gaborcsardi** [comment]
@hadley It is a problem in r-release I think, but not in r-devel. Unless there was a change since wch/r-source@e7cf1f0

...

There was no change it seems: https://github.com/wch/r-source/commits/e7cf1f06c0cdf439eca9d561b84316a44089e142/src/library/tools/R/check.R

So yes, `NEWS.md` and `inst/NEWS.md` are picked up by r-devel:
* they convert it to HTML with pandoc
* they'll put it on the CRAN website (maybe not until R 3.3.0)
* you'll get an email from CRAN if pandoc fails :)

**Comment by hadley** [comment]
So that means `NEWS.md` submission should be ok now, right? (Because CRAN runs R CMD check with R-devel)

**Comment by gaborcsardi** [comment]
YEs, I think so. (Except for the pandoc failures. :)
